package wyjc.compiler;

import java.io.FileOutputStream;
import java.io.IOException;
import java.util.*;

import wyil.ModuleLoader;
import wyil.lang.Module;
import wyil.util.Logger;
import wyil.io.*;
import wyjvm.io.ClassFileWriter;
import wyjvm.lang.ClassFile;
import wyjvm.util.DeadCodeElimination;
import wyjvm.util.Validation;

public class ClassWriter implements Compiler.Stage {
	private ClassFileBuilder classBuilder;
	private final boolean validate;
	private final boolean deadCode;
	
	public ClassWriter(ModuleLoader loader) {
		this(loader,Collections.EMPTY_MAP);
	}
	
	public ClassWriter(ModuleLoader loader, Map<String, String> options) {
		classBuilder = new ClassFileBuilder(loader, wyjc.Main.MAJOR_VERSION,
				wyjc.Main.MINOR_VERSION);
		validate = !options.containsKey("nvalidate");
		deadCode = !options.containsKey("ndeadcode");
	}	
	
	public String name() {
		return "class file writer";
	}
	
	public Module process(Module m, Logger logout) {
		long start = System.currentTimeMillis();
		ClassFile file = classBuilder.build(m);
		
		if(validate) {			
			// validate generated bytecode
			new Validation().apply(file);
		}
		if(deadCode) {
			// eliminate any dead code that was introduced.		
			new DeadCodeElimination().apply(file);
		}
		
		// calculate filename
		String filename = m.filename().replace(".whiley", ".class");
		try {
			FileOutputStream out = new FileOutputStream(filename);
			ClassFileWriter writer = new ClassFileWriter(out,null);
			writer.write(file);
			logout.logTimedMessage("[" + m.filename() + "] class file written",
					System.currentTimeMillis() - start);
		} catch(IOException ex) {
			logout.logTimedMessage("[" + m.filename()
					+ "] failed writing class file (" + ex.getMessage() + ")",
					System.currentTimeMillis() - start);
		}
		return m;
	}	
	
}
