package wyjc.compiler;

import java.io.FileOutputStream;
import java.io.IOException;
import java.util.*;

import wyil.ModuleLoader;
import wyil.lang.Module;
import wyil.util.Logger;
import wyil.io.*;
import wyjvm.io.*;
import wyjvm.lang.ClassFile;
import wyjvm.util.DeadCodeElimination;
import wyjvm.util.Validation;

public class JvmBytecodeWriter implements Compiler.Stage {
	private ClassFileBuilder classBuilder;

	public JvmBytecodeWriter(ModuleLoader loader, Map<String, String> options) {
		classBuilder = new ClassFileBuilder(loader, wyjc.Main.MAJOR_VERSION,
				wyjc.Main.MINOR_VERSION);
	}
	
	public String name() {
		return "jvm file writer";
	}
	
	public Module process(Module m, Logger logout) {
		long start = System.currentTimeMillis();		
		ClassFile file = classBuilder.build(m);				
		// validate generated bytecode
		new Validation().apply(file);
		// eliminate any dead code that was introduced.		
		new DeadCodeElimination().apply(file);		
		
		// calculate filename
		String filename = m.filename().replace(".whiley", ".jvm");
		try {
			FileOutputStream out = new FileOutputStream(filename);
			BytecodeFileWriter writer = new BytecodeFileWriter(out,null);
			writer.write(file);
			out.flush();
			logout.logTimedMessage("[" + m.filename() + "] jvm bytecode file written",
					System.currentTimeMillis() - start);
		} catch(IOException ex) {
			logout.logTimedMessage("[" + m.filename()
					+ "] failed writing jvm bytecode file (" + ex.getMessage() + ")",
					System.currentTimeMillis() - start);
		}
		return m;
	}	
	
}
