bool f(char c):
    return c <= '9'

void System::main([string] args):
    x = f('0')    
    out.println(str(x))
    x = f('1')    
    out.println(str(x))
    x = f('2')    
    out.println(str(x))
    x = f('3')    
    out.println(str(x))
    x = f('4')    
    out.println(str(x))
    x = f('5')    
    out.println(str(x))
    x = f('6')    
    out.println(str(x))
    x = f('7')    
    out.println(str(x))
    x = f('8')    
    out.println(str(x))
    x = f('9')    
    out.println(str(x))
    x = f('a')    
    out.println(str(x))
    x = f('b')    
    out.println(str(x))
    x = f('c')    
    out.println(str(x))
    x = f('d')    
    out.println(str(x))
    x = f('e')    
    out.println(str(x))
